/*подсказка - номер этажа*/
        $('.e3f5').hover(
            function(){
                $('.sign35').css('display','block');
            },
            function(){
                $('.sign35').css('display','none');
            }
        );
        $('.e3f6').hover(
            function(){
                $('.sign36').css('display','block');
            },
            function(){
                $('.sign36').css('display','none');
            }
        );
        $('.e3f7').hover(
            function(){
                $('.sign37').css('display','block');
            },
            function(){
                $('.sign37').css('display','none');
            }
        );
        $('.e2f9').hover(
            function(){
                $('.sign29').css('display','block');
            },
            function(){
                $('.sign29').css('display','none');
            }
        );
        $('.e2f10').hover(
            function(){
                $('.sign210').css('display','block');
            },
            function(){
                $('.sign210').css('display','none');
            }
        );
        $('.e2f11').hover(
            function(){
                $('.sign211').css('display','block');
            },
            function(){
                $('.sign211').css('display','none');
            }
        );
        $('.e2f12').hover(
            function(){
                $('.sign212').css('display','block');
            },
            function(){
                $('.sign212').css('display','none');
            }
        );
        $('.e2f13').hover(
            function(){
                $('.sign213').css('display','block');
            },
            function(){
                $('.sign213').css('display','none');
            }
        );
        $('.e2f14').hover(
            function(){
                $('.sign214').css('display','block');
            },
            function(){
                $('.sign214').css('display','none');
            }
        );
        $('.e2f15').hover(
            function(){
                $('.sign215').css('display','block');
            },
            function(){
                $('.sign215').css('display','none');
            }
        );
        $('.e1f1').hover(
            function(){
                $('.sign11').css('display','block');
            },
            function(){
                $('.sign11').css('display','none');
            }
        );
        $('.e1f2').hover(
            function(){
                $('.sign12').css('display','block');
            },
            function(){
                $('.sign12').css('display','none');
            }
        );
        $('.e1f3').hover(
            function(){
                $('.sign13').css('display','block');
            },
            function(){
                $('.sign13').css('display','none');
            }
        );
        $('.e1f4').hover(
            function(){
                $('.sign14').css('display','block');
            },
            function(){
                $('.sign14').css('display','none');
            }
        );
        $('.e1f5').hover(
            function(){
                $('.sign15').css('display','block');
            },
            function(){
                $('.sign15').css('display','none');
            }
        );
        $('.e1f6').hover(
            function(){
                $('.sign16').css('display','block');
            },
            function(){
                $('.sign16').css('display','none');
            }
        );
        $('.e1f7').hover(
            function(){
                $('.sign17').css('display','block');
            },
            function(){
                $('.sign17').css('display','none');
            }
        );
        $('.e1f8').hover(
            function(){
                $('.sign18').css('display','block');
            },
            function(){
                $('.sign18').css('display','none');
            }
        );
        $('.e1f9').hover(
            function(){
                $('.sign19').css('display','block');
            },
            function(){
                $('.sign19').css('display','none');
            }
        );
        $('.e1f10').hover(
            function(){
                $('.sign110').css('display','block');
            },
            function(){
                $('.sign110').css('display','none');
            }
        );
        $('.e1f11').hover(
            function(){
                $('.sign111').css('display','block');
            },
            function(){
                $('.sign111').css('display','none');
            }
        );
        $('.e1f12').hover(
            function(){
                $('.sign112').css('display','block');
            },
            function(){
                $('.sign112').css('display','none');
            }
        );
        $('.e1f13').hover(
            function(){
                $('.sign113').css('display','block');
            },
            function(){
                $('.sign113').css('display','none');
            }
        );
        $('.e1f14').hover(
            function(){
                $('.sign114').css('display','block');
            },
            function(){
                $('.sign114').css('display','none');
            }
        );
        $('.e1f15').hover(
            function(){
                $('.sign115').css('display','block');
            },
            function(){
                $('.sign115').css('display','none');
            }
        );
        $('.e1f16').hover(
            function(){
                $('.sign116').css('display','block');
            },
            function(){
                $('.sign116').css('display','none');
            }
        );